[package]
name = "my_os"
version = "0.1.0"
edition = "2018"
authors = ["Adam Brutsaert <brutsaertadam@yahoo.fr>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"
